# Generated by Django 5.2.3 on 2025-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='username',
        ),
    ]
