# Generated by Django 5.2.3 on 2025-06-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_rename_user_task_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='user',
        ),
    ]
